# Generated by Django 4.1.4 on 2023-01-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_name', models.TextField(max_length=200)),
                ('file_name', models.TextField(max_length=200)),
            ],
        ),
    ]
